### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/alerts#1]
I think RSS should be supported so that it can be plugged into http://pl6anet.org/

**Comment by zoffixznet** [comment]
Those are all blogs.

**Comment by AlexDaniel** [comment]
Not sure I understand your comment. Sure, but so? Wouldn't it be great to have alerts in the same feed?  And if not, then who would specifically check alert.perl6.org subdomain? IIRC pl6anet is quite popular, so having alerts there is going to reach enough people (which is exactly what we want?).

**Comment by zoffixznet** [comment]
> Sure, but so?

So why spam non-blog content into blog space?

Could we at least get something up first before starting with all this bikeshedding?

**Comment by AlexDaniel** [comment]
🤷
